apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: crewai-cerebras
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: crewai-cerebras-backend:latest
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: crewai-config
              key: DATABASE_URL
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: crewai-config
              key: REDIS_URL
        - name: CEREBRAS_API_KEY
          valueFrom:
            secretKeyRef:
              name: crewai-secrets
              key: CEREBRAS_API_KEY
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: crewai-secrets
              key: SECRET_KEY
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: crewai-secrets
              key: JWT_SECRET_KEY
        - name: FRONTEND_URL
          valueFrom:
            configMapKeyRef:
              name: crewai-config
              key: FRONTEND_URL
        - name: BACKEND_URL
          valueFrom:
            configMapKeyRef:
              name: crewai-config
              key: BACKEND_URL
        - name: DEBUG
          valueFrom:
            configMapKeyRef:
              name: crewai-config
              key: DEBUG
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: crewai-config
              key: ENVIRONMENT
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: crewai-cerebras
spec:
  selector:
    app: backend
  ports:
  - port: 8000
    targetPort: 8000