apiVersion: v1
kind: ConfigMap
metadata:
  name: crewai-config
  namespace: crewai-cerebras
data:
  DATABASE_URL: "postgresql://postgres:password@postgres-service:5432/crewai_db"
  REDIS_URL: "redis://redis-service:6379"
  FRONTEND_URL: "http://localhost:3000"
  BACKEND_URL: "http://localhost:8000"
  DEBUG: "False"
  ENVIRONMENT: "production"