apiVersion: v1
kind: Secret
metadata:
  name: crewai-secrets
  namespace: crewai-cerebras
type: Opaque
data:
  CEREBRAS_API_KEY: Y3NrLWZkOTU1NHdmNGpkbjk5eWQ4d2Q1ajNjeWhjd21uNTNmOHZ0OG53bmg1NDQ5ZWs1
  SECRET_KEY: eW91ci1zdXBlci1zZWNyZXQta2V5LWNoYW5nZS10aGlzLWluLXByb2R1Y3Rpb24=
  JWT_SECRET_KEY: eW91ci1qd3Qtc2VjcmV0LWtleQ==